# Generated by Django 2.0.8 on 2019-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alternate_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ref_id', models.CharField(max_length=50)),
                ('product_alternate_unit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'alternate_units',
            },
        ),
        migrations.CreateModel(
            name='categorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=50)),
                ('product_brand', models.CharField(blank=True, max_length=50)),
                ('product_unit_type', models.CharField(max_length=50)),
                ('product_default_unit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categorisation',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_code', models.IntegerField()),
                ('product_hsn', models.IntegerField(null=True)),
                ('category_ref', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('brand_ref', models.CharField(max_length=50)),
                ('unit_type_ref', models.CharField(max_length=50)),
                ('product_stock', models.CharField(max_length=50)),
                ('product_low_stock_limit', models.IntegerField()),
                ('product_cost', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_wholesale_price', models.IntegerField(null=True)),
                ('product_tax_category', models.IntegerField(null=True)),
                ('product_tax_amount', models.IntegerField(null=True)),
                ('product_discount', models.IntegerField()),
                ('alternate_unit_ref', models.CharField(max_length=50, null=True)),
                ('product_tax_satus', models.CharField(max_length=10, null=True)),
                ('product_alternate_cost', models.IntegerField(null=True)),
                ('product_alternate_price', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
