# Generated by Django 2.1.7 on 2019-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_tax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_tax_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
