# Generated by Django 2.2.3 on 2019-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190411_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_code', models.IntegerField()),
                ('product_hsn', models.IntegerField(null=True)),
                ('category_ref', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('brand_ref', models.CharField(max_length=50, null=True)),
                ('unit_type_ref', models.CharField(max_length=50)),
                ('product_stock', models.CharField(max_length=50)),
                ('product_low_stock_limit', models.IntegerField()),
                ('product_cost', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('product_wholesale_price', models.IntegerField(null=True)),
                ('product_tax_category', models.IntegerField(null=True)),
                ('product_tax_amount', models.CharField(max_length=50)),
                ('product_discount', models.IntegerField()),
                ('alternate_unit_ref', models.CharField(max_length=50, null=True)),
                ('product_tax_satus', models.CharField(max_length=10, null=True)),
                ('product_alternate_cost', models.IntegerField(null=True)),
                ('product_alternate_price', models.IntegerField(null=True)),
                ('price_tax', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_ref',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_ref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
