# Generated by Django 2.2.3 on 2019-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190714_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=50),
        ),
    ]
