# Generated by Django 2.2.3 on 2019-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190718_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='product_code',
            field=models.CharField(max_length=20),
        ),
    ]
