# Generated by Django 2.2.3 on 2019-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190725_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorisation',
            name='product_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categorisation',
            name='product_default_unit_prefix',
            field=models.CharField(max_length=50),
        ),
    ]
