# Generated by Django 2.2.3 on 2019-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190725_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_integer_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_products',
            name='product_integer_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
