# Generated by Django 2.2.3 on 2019-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_products_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_products',
            name='final_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
