# Generated by Django 2.2.3 on 2019-08-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_sub_products_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='final_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='final_price',
            field=models.CharField(max_length=50),
        ),
    ]
