# Generated by Django 2.2.3 on 2019-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190813_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='final_wholesale_price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_products',
            name='final_wholesale_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
