# Generated by Django 2.2.3 on 2019-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190817_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='taxable_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_products',
            name='taxable_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
