# Generated by Django 2.2.3 on 2019-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190817_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wholesale_taxable_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_products',
            name='wholesale_taxable_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
