# Generated by Django 2.2.3 on 2019-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alternate_units_product_alternate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate_cost_price',
            name='taxable_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
