# Generated by Django 2.2.3 on 2019-10-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alternate_cost_price_taxable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate_units',
            name='product_alternate_unit_prifix',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
