# Generated by Django 2.2.3 on 2019-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alternate_units_product_alternate_unit_prifix'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternate_cost_price',
            name='price_without_tax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
