# Generated by Django 2.2.3 on 2019-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alternate_cost_price_price_without_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wholesaleprice_without_tax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_products',
            name='wholesaleprice_without_tax',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
