# Generated by Django 2.2.3 on 2019-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20191110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_alternate_cost',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_alternate_price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='product_alternate_cost',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='product_alternate_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
