# Generated by Django 2.2.3 on 2019-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20191120_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_cost_price',
            name='product_cost',
            field=models.CharField(max_length=10),
        ),
    ]
