# Generated by Django 2.2.3 on 2019-11-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20191120_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_cost_price',
            name='product_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_alternate_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_alternate_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='product_alternate_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='product_alternate_price',
            field=models.IntegerField(null=True),
        ),
    ]
