# Generated by Django 2.1.7 on 2019-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_phone', models.IntegerField()),
                ('store_gst', models.CharField(max_length=50)),
                ('store_website', models.CharField(max_length=50)),
                ('store_email', models.CharField(max_length=50)),
                ('store_adress', models.CharField(max_length=200)),
                ('store_state', models.CharField(max_length=50)),
                ('store_log0', models.ImageField(upload_to='')),
            ],
        ),
    ]
