# Generated by Django 2.1.7 on 2019-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_details',
            name='store_log0',
        ),
        migrations.AddField(
            model_name='store_details',
            name='store_logo',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
