# Generated by Django 2.1.7 on 2019-04-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_billing', '0004_auto_20190404_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_details',
            name='store_logo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
