# Generated by Django 2.1.7 on 2019-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_billing', '0005_auto_20190405_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_details',
            name='store_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
