# Generated by Django 2.2.3 on 2019-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_billing', '0006_auto_20190405_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_details',
            name='store_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_details',
            name='store_logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
