# Generated by Django 2.2.3 on 2019-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_billing', '0007_auto_20190718_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_details',
            name='cess_status',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store_details',
            name='store_phone',
            field=models.CharField(max_length=15),
        ),
    ]
