# Generated by Django 2.1.7 on 2019-03-27 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_returned',
            name='sale_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 27, 14, 45, 36, 149372)),
        ),
    ]
