# Generated by Django 2.1.7 on 2019-03-28 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_auto_20190327_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_returned',
            name='sale_return_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 28, 16, 27, 21, 230837)),
        ),
    ]
