# Generated by Django 2.1.7 on 2019-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_create_sales_final_sale_invoice_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_sales_final',
            name='sale_invoice_ref',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_sales_final',
            name='sales_credit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_sales_final',
            name='sales_debit',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_sales_table',
            name='sales_invoice_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
