# Generated by Django 2.1.7 on 2019-03-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190327_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_sales_final',
            name='sales_credit',
        ),
        migrations.RemoveField(
            model_name='create_sales_final',
            name='sales_debit',
        ),
    ]
