# Generated by Django 2.0.8 on 2019-03-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190327_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percent', models.IntegerField()),
                ('sale_date', models.DateField(null=True)),
                ('total_tax_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
