# Generated by Django 2.1.7 on 2019-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxes',
            name='price_tax_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
