# Generated by Django 2.2.3 on 2019-08-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190719_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_sales_final',
            name='sale_return_status',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
