# Generated by Django 2.2.3 on 2019-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_create_sales_final_sale_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_sales_final',
            name='sales_taxable_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_wholesale_sales_final',
            name='sales_taxable_amount',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
