# Generated by Django 2.2.3 on 2019-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190820_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_sales_final',
            name='sales_printing',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_wholesale_sales_final',
            name='sales_printing',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
