# Generated by Django 2.2.3 on 2019-10-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20190912_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_sales_final',
            name='report_printing',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_wholesale_sales_final',
            name='report_printing',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
