# Generated by Django 2.2.3 on 2019-10-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20191021_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_sales_final',
            name='report_printing',
        ),
        migrations.RemoveField(
            model_name='create_wholesale_sales_final',
            name='report_printing',
        ),
    ]
