# Generated by Django 2.2.3 on 2019-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20191021_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('taxable_amount', models.CharField(max_length=50)),
                ('tax_percent', models.CharField(max_length=50)),
                ('cgst', models.CharField(max_length=50)),
                ('sgst', models.CharField(max_length=50)),
            ],
        ),
    ]
