# Generated by Django 2.2.3 on 2019-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_reports_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='invoice_no',
            field=models.IntegerField(),
        ),
    ]
